// Spinonym puzzle bank.
// Add puzzles here without touching the game code. Each puzzle needs:
//   type   : one of the 18 wheel types (see TYPES in index.html)
//   clue   : the big word or phrase on the card
//   sub    : the line under it (a nudge, not the answer)
//   answer : one word, lower case
//   close  : other fair answers, space-separated. Guessing one is free and checks no letters.
//   hint   : optional mask, e.g. "___ngy". Without one, the hint shows the last half of the word.
//   note   : optional line shown on the result (e.g. what an acronym stands for)
// Each type cycles through its own puzzles, so a type with few puzzles repeats sooner.

const PUZZLES = [
  // ---- Meaning ----
  {type:"antonym", clue:"Generous", sub:"It's a describing word.", answer:"stingy",
   close:"mean miserly tight cheap selfish greedy ungenerous parsimonious tightfisted mingy"},
  {type:"antonym", clue:"Ancient", sub:"It's a describing word.", answer:"modern",
   close:"new recent current contemporary young fresh novel latest"},
  {type:"antonym", clue:"Expand", sub:"It's a doing word.", answer:"shrink",
   close:"contract reduce narrow decrease dwindle lessen compress deflate"},
  {type:"antonym", clue:"Victory", sub:"It's a thing word.", answer:"defeat",
   close:"loss failure"},
  {type:"antonym", clue:"Arrive", sub:"It's a doing word.", answer:"depart",
   close:"leave go exit quit"},
  {type:"antonym", clue:"Freeze", sub:"It's a doing word.", answer:"thaw",
   close:"melt warm heat defrost"},
  {type:"antonym", clue:"Accept", sub:"It's a doing word.", answer:"refuse",
   close:"reject decline deny"},

  {type:"hypernym", clue:"Oak · Ash · Birch", sub:"One word covers all three.", answer:"tree", close:"plant wood timber"},
  {type:"hypernym", clue:"Robin · Wren · Thrush", sub:"One word covers all three.", answer:"bird", close:"songbird animal"},
  {type:"hypernym", clue:"Hammer · Saw · Spanner", sub:"One word covers all three.", answer:"tool", close:"equipment implement"},
  {type:"hypernym", clue:"Piano · Violin · Trumpet", sub:"One word covers all three.", answer:"instrument", close:"music"},

  {type:"hyponym", clue:"Dog", sub:"A curly-coated breed, famous for fancy haircuts.", answer:"poodle",
   close:"labrador spaniel terrier collie beagle dachshund bulldog greyhound whippet retriever pug corgi"},
  {type:"hyponym", clue:"Cheese", sub:"Named after a village in Somerset.", answer:"cheddar",
   close:"stilton brie wensleydale cheshire gouda edam camembert feta"},
  {type:"hyponym", clue:"Tree", sub:"Its leaf is on Canada's flag.", answer:"maple",
   close:"oak ash birch elm willow pine beech sycamore"},
  {type:"hyponym", clue:"Bread", sub:"Italian, flat, and named after a slipper.", answer:"ciabatta",
   close:"focaccia baguette bloomer bagel brioche sourdough naan pitta"},

  {type:"meronym", clue:"Bicycle", sub:"The bit you sit on.", answer:"saddle",
   close:"seat wheel pedal chain brake bell spoke tyre frame handlebar"},
  {type:"meronym", clue:"Book", sub:"The edge you see when it's on a shelf.", answer:"spine",
   close:"cover page chapter jacket"},
  {type:"meronym", clue:"Flower", sub:"One of the coloured bits round the middle.", answer:"petal",
   close:"stem leaf bud pollen"},
  {type:"meronym", clue:"House", sub:"Where the smoke goes out.", answer:"chimney",
   close:"roof flue door window wall"},

  {type:"kangaroo-word", clue:"Rapscallion", sub:"A word meaning the same hides inside it, letters in order.", answer:"rascal"},
  {type:"kangaroo-word", clue:"Instructor", sub:"A word meaning the same hides inside it, letters in order.", answer:"tutor"},
  {type:"kangaroo-word", clue:"Destruction", sub:"A word meaning the same hides inside it, letters in order.", answer:"ruin"},
  {type:"kangaroo-word", clue:"Encourage", sub:"A word meaning the same hides inside it, letters in order.", answer:"urge"},

  {type:"collective-noun", clue:"Crows", sub:"A ____ of crows. It sounds sinister.", answer:"murder", close:"flock"},
  {type:"collective-noun", clue:"Owls", sub:"A ____ of owls. Sounds like they make the laws.", answer:"parliament", close:"flock"},
  {type:"collective-noun", clue:"Lions", sub:"A ____ of lions.", answer:"pride", close:"group troop"},
  {type:"collective-noun", clue:"Geese", sub:"A ____ of geese, when they're on the ground.", answer:"gaggle", close:"flock skein"},

  // ---- Sound & spelling ----
  {type:"anagram", clue:"Silent", sub:"Use every letter. It means: pay attention.", answer:"listen", close:"enlist tinsel inlets"},
  {type:"anagram", clue:"Earth", sub:"Use every letter. It's something that beats.", answer:"heart", close:"hater"},
  {type:"anagram", clue:"Dusty", sub:"Use every letter. It's a room for reading.", answer:"study"},
  {type:"anagram", clue:"Elbow", sub:"Use every letter. It means underneath.", answer:"below", close:"bowel"},
  {type:"anagram", clue:"Lemon", sub:"Use every letter. It's a big, juicy fruit.", answer:"melon"},
  {type:"anagram", clue:"Teacher", sub:"Use every letter. Someone who breaks the rules.", answer:"cheater", close:"hectare"},
  {type:"anagram", clue:"Inch", sub:"Use every letter. It's part of your face.", answer:"chin"},

  {type:"homophone", clue:"Knight", sub:"Same sound, different spelling: when the sun's gone down.", answer:"night"},
  {type:"homophone", clue:"Flour", sub:"Same sound, different spelling: it grows in the garden.", answer:"flower"},
  {type:"homophone", clue:"Bare", sub:"Same sound, different spelling: a big furry animal.", answer:"bear"},
  {type:"homophone", clue:"Whole", sub:"Same sound, different spelling: a gap or opening.", answer:"hole"},
  {type:"homophone", clue:"Pair", sub:"Same sound, different spelling: a fruit.", answer:"pear", close:"pare"},
  {type:"homophone", clue:"Stare", sub:"Same sound, different spelling: one step of a flight.", answer:"stair"},

  {type:"homograph", clue:"A metal · To guide", sub:"One spelling covers both.", answer:"lead"},
  {type:"homograph", clue:"A dog's sound · A tree's skin", sub:"One spelling covers both.", answer:"bark"},
  {type:"homograph", clue:"A game · A fire stick", sub:"One spelling covers both.", answer:"match"},
  {type:"homograph", clue:"A flying mammal · For hitting a ball", sub:"One spelling covers both.", answer:"bat"},

  {type:"palindrome", clue:"Midday", sub:"It reads the same backwards.", answer:"noon"},
  {type:"palindrome", clue:"A small, narrow boat", sub:"It reads the same backwards.", answer:"kayak"},
  {type:"palindrome", clue:"Flat and even", sub:"It reads the same backwards.", answer:"level"},
  {type:"palindrome", clue:"To do with a town", sub:"It reads the same backwards.", answer:"civic"},

  {type:"semordnilap", clue:"Halt", sub:"Spelt backwards, it's what you cook in.", answer:"stop", close:"cease pause"},
  {type:"semordnilap", clue:"Prize", sub:"Spelt backwards, it's a sliding box in a chest.", answer:"reward", close:"award trophy medal"},
  {type:"semordnilap", clue:"Wicked", sub:"Spelt backwards, it's what you do while you're alive.", answer:"evil", close:"bad wrong sinful"},
  {type:"semordnilap", clue:"Pieces", sub:"Spelt backwards, it's a band with a buckle.", answer:"parts", close:"bits"},

  {type:"rhyming-slang", clue:"Apples and pears", sub:"Cockney rhyming slang. Most houses have them.", answer:"stairs", close:"steps"},
  {type:"rhyming-slang", clue:"Dog and bone", sub:"Cockney rhyming slang. You might be on it now.", answer:"phone", close:"telephone mobile"},
  {type:"rhyming-slang", clue:"Plates of meat", sub:"Cockney rhyming slang. You stand on them.", answer:"feet"},
  {type:"rhyming-slang", clue:"Butcher's hook", sub:"Cockney rhyming slang. \"Have a butcher's.\"", answer:"look", close:"glance peek"},
  {type:"rhyming-slang", clue:"Pork pies", sub:"Cockney rhyming slang. Don't tell them.", answer:"lies", close:"fibs"},

  // ---- Names ----
  {type:"eponym", clue:"An earl who ate at the card table", sub:"It's named after him. Lunch for millions.", answer:"sandwich"},
  {type:"eponym", clue:"A duke's tall boots", sub:"It's named after him. Good in puddles.", answer:"wellington", close:"welly wellie"},
  {type:"eponym", clue:"An earl's knitted jacket", sub:"It's named after him. Buttons up the front.", answer:"cardigan"},
  {type:"eponym", clue:"A Russian ballerina", sub:"It's named after her. Meringue, cream and fruit.", answer:"pavlova"},
  {type:"eponym", clue:"A land agent everyone shunned", sub:"It's named after him. Refusing to deal with someone.", answer:"boycott"},
  {type:"eponym", clue:"Sir Robert Peel's police", sub:"It's named after him. A friendly word for a copper.", answer:"bobby"},

  {type:"pseudonym", clue:"Eric Arthur Blair", sub:"He wrote Animal Farm as George ____.", answer:"orwell", free:true},
  {type:"pseudonym", clue:"Samuel Clemens", sub:"He wrote Tom Sawyer as Mark ____.", answer:"twain", free:true},
  {type:"pseudonym", clue:"Mary Ann Evans", sub:"She wrote Middlemarch as George ____.", answer:"eliot", free:true},
  {type:"pseudonym", clue:"Norma Jeane Mortenson", sub:"She became Marilyn ____.", answer:"monroe", free:true},

  {type:"exonym", clue:"Deutschland", sub:"A country in Europe.", answer:"germany", free:true},
  {type:"exonym", clue:"Cymru", sub:"A country much closer to home.", answer:"wales", free:true},
  {type:"exonym", clue:"Nihon", sub:"An island country in Asia.", answer:"japan", free:true},
  {type:"exonym", clue:"Suomi", sub:"A country in the far north of Europe.", answer:"finland", free:true},

  // ---- Word-building ----
  {type:"acronym", clue:"Breathing gear for diving", sub:"Each letter stands for a word.", answer:"scuba",
   note:"Self-contained underwater breathing apparatus."},
  {type:"acronym", clue:"A beam of very bright light", sub:"Each letter stands for a word.", answer:"laser",
   note:"Light amplification by stimulated emission of radiation."},
  {type:"acronym", clue:"It spots planes with radio waves", sub:"Each letter stands for a word.", answer:"radar",
   note:"Radio detection and ranging."},
  {type:"acronym", clue:"Someone against building work near their home", sub:"Each letter stands for a word.", answer:"nimby",
   note:"Not in my back yard."},
  {type:"acronym", clue:"Four secret digits for your bank card", sub:"Each letter stands for a word.", answer:"pin",
   note:"Personal identification number."},

  {type:"portmanteau", clue:"Breakfast + Lunch", sub:"A late-morning meal.", answer:"brunch"},
  {type:"portmanteau", clue:"Smoke + Fog", sub:"Dirty city air.", answer:"smog"},
  {type:"portmanteau", clue:"Motor + Hotel", sub:"A roadside place to stay.", answer:"motel"},
  {type:"portmanteau", clue:"Chuckle + Snort", sub:"A gleeful laugh. Lewis Carroll made it up.", answer:"chortle"},
  {type:"portmanteau", clue:"Web + Log", sub:"An online diary.", answer:"blog"},
  {type:"portmanteau", clue:"Camera + Recorder", sub:"For filming holidays.", answer:"camcorder"},

  {type:"clipping", clue:"Influenza", sub:"Its everyday short form. You might catch it in winter.", answer:"flu"},
  {type:"clipping", clue:"Perambulator", sub:"Its everyday short form. For pushing a baby.", answer:"pram", close:"buggy pushchair"},
  {type:"clipping", clue:"Refrigerator", sub:"Its everyday short form. Keeps the milk cold.", answer:"fridge"},
  {type:"clipping", clue:"Hippopotamus", sub:"Its everyday short form. A big river animal.", answer:"hippo"},
  {type:"clipping", clue:"Gymnasium", sub:"Its everyday short form. Where you work out.", answer:"gym"},
];

// Name that nym: the bonus round. Three a day, in order, then it cycles.
// Uses glossary terms that aren't Easter eggs, so eggs stay a surprise.
const QUIZ = [
  {ex:"“Abso-bloody-lutely”", a:"Tmesis", o:["Spoonerism","Tmesis","Portmanteau","Zeugma"],
   why:"Tmesis: splitting a word in two by dropping another word into the middle.", id:"tmesis"},
  {ex:"“She lost her keys and her temper”", a:"Zeugma", o:["Oxymoron","Zeugma","Simile","Litotes"],
   why:"Zeugma: one word doing two jobs at once. Here “lost” means two different things.", id:"zeugma"},
  {ex:"“Fighting a liar” (for lighting a fire)", a:"Spoonerism", o:["Spoonerism","Malapropism","Mondegreen","Anagram"],
   why:"Spoonerism: swapping the first sounds of two words.", id:"spoonerism"},
  {ex:"“Deafening silence”", a:"Oxymoron", o:["Hyperbole","Oxymoron","Euphemism","Metaphor"],
   why:"Oxymoron: two words with opposite meanings used together.", id:"oxymoron"},
  {ex:"“Not bad at all” (meaning really good)", a:"Litotes", o:["Litotes","Euphemism","Idiom","Hyperbole"],
   why:"Litotes: saying something by denying its opposite. A very British habit.", id:"litotes"},
  {ex:"“I've told you a million times”", a:"Hyperbole", o:["Metaphor","Hyperbole","Idiom","Simile"],
   why:"Hyperbole: deliberate exaggeration.", id:"hyperbole"},
  {ex:"“As brave as a lion”", a:"Simile", o:["Metaphor","Simile","Alliteration","Idiom"],
   why:"Simile: comparing two things using “like” or “as”.", id:"simile"},
  {ex:"“Time is money”", a:"Metaphor", o:["Simile","Metaphor","Idiom","Metonym"],
   why:"Metaphor: saying one thing is another.", id:"metaphor"},
  {ex:"Sizzle · Buzz · Splash", a:"Onomatopoeia", o:["Alliteration","Onomatopoeia","Assonance","Tautonym"],
   why:"Onomatopoeia: words that sound like the noise they describe.", id:"onomatopoeia"},
  {ex:"“Peter Piper picked a peck of pickled peppers”", a:"Alliteration", o:["Assonance","Alliteration","Consonance","Pangram"],
   why:"Alliteration: words close together starting with the same sound.", id:"alliteration"},
  {ex:"“The quick brown fox jumps over the lazy dog”", a:"Pangram", o:["Pangram","Lipogram","Alliteration","Isogram"],
   why:"Pangram: a sentence that uses every letter of the alphabet.", id:"pangram"},
  {ex:"Tangerine · Dream", a:"Assonance", o:["Consonance","Assonance","Oronym","Homophone"],
   why:"Assonance: the same vowel sound with different endings. A kind of half rhyme.", id:"assonance"},
  {ex:"Blank · Think", a:"Consonance", o:["Assonance","Alliteration","Consonance","Homograph"],
   why:"Consonance: the same consonant sounds with different vowels.", id:"consonance"},
  {ex:"“For all intensive purposes”", a:"Eggcorn", o:["Eggcorn","Malapropism","Mondegreen","Spoonerism"],
   why:"Eggcorn: a misheard phrase that still sort of makes sense.", id:"eggcorn"},
  {ex:"“She danced the flamingo” (for flamenco)", a:"Malapropism", o:["Eggcorn","Spoonerism","Malapropism","Oronym"],
   why:"Malapropism: using the wrong word because it sounds like the right one.", id:"malapropism"},
  {ex:"“Gladly the cross-eyed bear” (from a hymn)", a:"Mondegreen", o:["Oronym","Mondegreen","Eggcorn","Malapropism"],
   why:"Mondegreen: a misheard line from a song, poem or hymn.", id:"mondegreen"},
  {ex:"Ice cream · I scream", a:"Oronym", o:["Homophone","Homograph","Oronym","Mondegreen"],
   why:"Oronym: a phrase that sounds exactly like a different phrase.", id:"oronym"},
  {ex:"“Short” is a short word", a:"Autological word", o:["Palindrome","Autological word","Tautonym","Isogram"],
   why:"Autological word: a word that describes itself.", id:"autological-word"},
  {ex:"Lumberjacks (no letter appears twice)", a:"Isogram", o:["Pangram","Lipogram","Anagram","Isogram"],
   why:"Isogram: a word where no letter is repeated.", id:"isogram"},
  {ex:"Usain Bolt, the sprinter", a:"Aptronym", o:["Aptronym","Eponym","Pseudonym","Mononym"],
   why:"Aptronym: a name that suits the person's job.", id:"aptronym"},
  {ex:"Adele · Madonna · Pelé", a:"Mononym", o:["Pseudonym","Mononym","Aptronym","Exonym"],
   why:"Mononym: someone known by just one name.", id:"mononym"},
  {ex:"“Whale-road” for the sea", a:"Kenning", o:["Metaphor","Portmanteau","Kenning","Calque"],
   why:"Kenning: a poetic two-word name for something, from Old English and Norse poetry.", id:"kenning"},
  {ex:"Couscous · Bonbon", a:"Tautonym", o:["Palindrome","Tautonym","Anagram","Semordnilap"],
   why:"Tautonym: a word made of the same part said twice.", id:"tautonym"},
  {ex:"“Unkempt”, but nobody is ever “kempt”", a:"Unpaired word", o:["Antonym","Contronym","Oxymoron","Unpaired word"],
   why:"Unpaired word: its plain partner has fallen out of use.", id:"unpaired-word"},
  // ---- Added 10 Oct: weeks 2 to 4. Always add new questions at the end, so earlier days keep their sets. ----
  {ex:"Skint · Broke · Hard up", a:"Synonym", o:["Antonym","Synonym","Homonym","Hypernym"],
   why:"Synonym: words with the same or a very similar meaning.", id:"synonym"},
  {ex:"Dust: to sprinkle it on, or to wipe it off", a:"Contronym", o:["Homograph","Contronym","Oxymoron","Heteronym"],
   why:"Contronym: one word with two opposite meanings.", id:"contronym"},
  {ex:"Someone from Liverpool is a Liverpudlian", a:"Demonym", o:["Toponym","Eponym","Demonym","Exonym"],
   why:"Demonym: the name for people from a place.", id:"demonym"},
  {ex:"Cheddar, from the village in Somerset", a:"Toponym", o:["Eponym","Toponym","Demonym","Endonym"],
   why:"Toponym: a word that comes from a place name.", id:"toponym"},
  {ex:"“Landline”, once mobiles came along", a:"Retronym", o:["Retronym","Neologism","Clipping","Backronym"],
   why:"Retronym: a new name for an old thing, needed because something newer arrived.", id:"retronym"},
  {ex:"SOS as “Save Our Souls”", a:"Backronym", o:["Acronym","Initialism","Backronym","Retronym"],
   why:"Backronym: a phrase invented afterwards to fit a word that already existed.", id:"backronym"},
  {ex:"Polish your shoes · Polish food", a:"Capitonym", o:["Homophone","Capitonym","Heteronym","Contronym"],
   why:"Capitonym: a word that changes meaning when it gets a capital letter.", id:"capitonym"},
  {ex:"Take a bow · Tie a bow", a:"Heteronym", o:["Heteronym","Homophone","Synonym","Capitonym"],
   why:"Heteronym: spelt the same, said differently, with a different meaning.", id:"heteronym"},
  {ex:"A bat that flies · A cricket bat", a:"Homonym", o:["Homophone","Heteronym","Homonym","Antonym"],
   why:"Homonym: spelt and said the same, with a different meaning.", id:"homonym"},
  {ex:"Bob for Robert", a:"Hypocorism", o:["Pseudonym","Hypocorism","Clipping","Mononym"],
   why:"Hypocorism: a pet name or friendly short form of a name.", id:"hypocorism"},
  {ex:"BBC, said letter by letter", a:"Initialism", o:["Acronym","Initialism","Clipping","Backronym"],
   why:"Initialism: like an acronym, but you say each letter.", id:"initialism"},
  {ex:"Operation Overlord, for the D-Day landings", a:"Cryptonym", o:["Pseudonym","Cryptonym","Eponym","Toponym"],
   why:"Cryptonym: a code name used to keep something secret.", id:"cryptonym"},
  {ex:"Deutschland, as Germans call it", a:"Endonym", o:["Exonym","Endonym","Demonym","Toponym"],
   why:"Endonym: the name a place or people use for themselves.", id:"endonym"},
  {ex:"“Passed away”", a:"Euphemism", o:["Idiom","Euphemism","Litotes","Metaphor"],
   why:"Euphemism: a gentler way of saying something blunt.", id:"euphemism"},
  {ex:"“It's raining cats and dogs”", a:"Idiom", o:["Hyperbole","Metaphor","Idiom","Simile"],
   why:"Idiom: a phrase that means something different from its words.", id:"idiom"},
  {ex:"“Doomscrolling”, a word born in 2020", a:"Neologism", o:["Neologism","Clipping","Loanword","Retronym"],
   why:"Neologism: a newly invented word.", id:"neologism"},
  {ex:"Café, borrowed straight from French", a:"Loanword", o:["Calque","Loanword","Eponym","Clipping"],
   why:"Loanword: a word borrowed from another language and used as it is.", id:"loanword"},
  {ex:"“Flea market”, from French marché aux puces", a:"Calque", o:["Loanword","Idiom","Calque","Kenning"],
   why:"Calque: a phrase translated word for word from another language.", id:"calque"},
  {ex:"A poem whose lines start C, A, T", a:"Acrostic", o:["Acronym","Acrostic","Anagram","Pangram"],
   why:"Acrostic: the first letter of each line spells out a word.", id:"acrostic"},
  {ex:"“The Crown”, meaning the monarchy", a:"Metonym", o:["Metaphor","Metonym","Meronym","Synonym"],
   why:"Metonym: something closely linked stands in for the real thing.", id:"metonym"},
  {ex:"A wheel, as part of a car", a:"Meronym", o:["Holonym","Hyponym","Meronym","Metonym"],
   why:"Meronym: a word for a part of something bigger.", id:"meronym"},
  {ex:"A car, as the whole that a wheel belongs to", a:"Holonym", o:["Holonym","Hypernym","Meronym","Homonym"],
   why:"Holonym: the whole that a part belongs to.", id:"holonym"},
  {ex:"Rose, tulip, daisy → flower", a:"Hypernym", o:["Hyponym","Hypernym","Holonym","Synonym"],
   why:"Hypernym: the umbrella word for a group.", id:"hypernym"},
  {ex:"Dog → poodle", a:"Hyponym", o:["Hypernym","Meronym","Hyponym","Eponym"],
   why:"Hyponym: one specific example from a group.", id:"hyponym"},
  {ex:"Stressed → desserts", a:"Semordnilap", o:["Palindrome","Anagram","Semordnilap","Spoonerism"],
   why:"Semordnilap: a word that spells a different word backwards.", id:"semordnilap"},
  {ex:"Masculine hides male", a:"Kangaroo word", o:["Kangaroo word","Anagram","Clipping","Tautonym"],
   why:"Kangaroo word: it hides a word with the same meaning inside, letters in order.", id:"kangaroo-word"},
  {ex:"A pod of dolphins", a:"Collective noun", o:["Kenning","Collective noun","Idiom","Hypernym"],
   why:"Collective noun: the word for a group of things.", id:"collective-noun"},
  {ex:"Barnet Fair, meaning hair", a:"Rhyming slang", o:["Spoonerism","Euphemism","Rhyming slang","Eggcorn"],
   why:"Rhyming slang: a phrase that stands in for a word it rhymes with.", id:"rhyming-slang"},
  {ex:"Leotard, after the acrobat Jules Léotard", a:"Eponym", o:["Toponym","Eponym","Loanword","Aptronym"],
   why:"Eponym: a word named after a real person.", id:"eponym"},
  {ex:"Stefani Germanotta performs as Lady Gaga", a:"Pseudonym", o:["Mononym","Hypocorism","Pseudonym","Cryptonym"],
   why:"Pseudonym: a made-up name used instead of a real one.", id:"pseudonym"},
  {ex:"Italy, for Italia", a:"Exonym", o:["Endonym","Exonym","Demonym","Calque"],
   why:"Exonym: the name outsiders use for a place.", id:"exonym"},
  {ex:"Nato, said as a word", a:"Acronym", o:["Initialism","Backronym","Acronym","Clipping"],
   why:"Acronym: a word made from first letters, said as a word.", id:"acronym"},
  {ex:"Spoon + fork = spork", a:"Portmanteau", o:["Portmanteau","Kenning","Tautonym","Neologism"],
   why:"Portmanteau: two words squashed into one.", id:"portmanteau"},
  {ex:"Exam, from examination", a:"Clipping", o:["Acronym","Clipping","Hypocorism","Initialism"],
   why:"Clipping: a longer word cut short.", id:"clipping"},
  {ex:"Sea · See", a:"Homophone", o:["Homograph","Homonym","Homophone","Oronym"],
   why:"Homophone: sounds the same, spelt differently.", id:"homophone"},
  {ex:"A tear in your eye · A tear in your shirt", a:"Homograph", o:["Homograph","Homophone","Contronym","Capitonym"],
   why:"Homograph: spelt the same, with a different meaning.", id:"homograph"},
  {ex:"Refer", a:"Palindrome", o:["Semordnilap","Palindrome","Isogram","Tautonym"],
   why:"Palindrome: reads the same forwards and backwards.", id:"palindrome"},
  {ex:"Night → thing", a:"Anagram", o:["Semordnilap","Spoonerism","Anagram","Kenning"],
   why:"Anagram: the same letters rearranged.", id:"anagram"},
  {ex:"Astronomer → moon starer", a:"Aptagram", o:["Aptagram","Spoonerism","Kenning","Semordnilap"],
   why:"Aptagram: an anagram whose new words suit the original.", id:"aptagram"},
  {ex:"Hot · Cold", a:"Antonym", o:["Synonym","Antonym","Contronym","Homonym"],
   why:"Antonym: a word with the opposite meaning.", id:"antonym"},
  {ex:"“Big, bold, brilliant Brighton”", a:"Alliteration", o:["Alliteration","Assonance","Consonance","Onomatopoeia"],
   why:"Alliteration: words close together starting with the same sound.", id:"alliteration"},
  {ex:"Worm · Swarm", a:"Half rhyme", o:["Homophone","Half rhyme","Oronym","Tautonym"],
   why:"Half rhyme: words that nearly rhyme, but not quite.", id:"half-rhyme"},
  {ex:"Bang · Crash · Wallop", a:"Onomatopoeia", o:["Alliteration","Hyperbole","Onomatopoeia","Tautonym"],
   why:"Onomatopoeia: words that sound like the noise they describe.", id:"onomatopoeia"},
  {ex:"“As cold as ice”", a:"Simile", o:["Simile","Metaphor","Hyperbole","Idiom"],
   why:"Simile: a comparison using “like” or “as”.", id:"simile"},
  {ex:"“The classroom was a zoo”", a:"Metaphor", o:["Simile","Metaphor","Metonym","Hyperbole"],
   why:"Metaphor: saying one thing is another.", id:"metaphor"},
  {ex:"“This bag weighs a ton”", a:"Hyperbole", o:["Litotes","Oxymoron","Idiom","Hyperbole"],
   why:"Hyperbole: deliberate exaggeration.", id:"hyperbole"},
  {ex:"Bittersweet", a:"Oxymoron", o:["Oxymoron","Antonym","Contronym","Tautonym"],
   why:"Oxymoron: opposites side by side.", id:"oxymoron"},
  {ex:"“Not the worst idea I've heard”", a:"Litotes", o:["Euphemism","Litotes","Hyperbole","Oxymoron"],
   why:"Litotes: saying something by denying its opposite.", id:"litotes"},
  {ex:"Gadsby: a whole novel without the letter e", a:"Lipogram", o:["Pangram","Isogram","Lipogram","Acrostic"],
   why:"Lipogram: writing that avoids one letter completely.", id:"lipogram"},
  {ex:"“Sphinx of black quartz, judge my vow”", a:"Pangram", o:["Alliteration","Pangram","Lipogram","Isogram"],
   why:"Pangram: a sentence using every letter of the alphabet.", id:"pangram"},
  {ex:"Uncopyrightable (no letter used twice)", a:"Isogram", o:["Isogram","Pangram","Palindrome","Lipogram"],
   why:"Isogram: a word with no repeated letters.", id:"isogram"},
  {ex:"“Noun” is a noun", a:"Autological word", o:["Tautonym","Homonym","Autological word","Palindrome"],
   why:"Autological word: a word that describes itself.", id:"autological-word"},
  {ex:"The poet William Wordsworth", a:"Aptronym", o:["Aptronym","Pseudonym","Eponym","Kenning"],
   why:"Aptronym: a name that suits what someone does.", id:"aptronym"},
  {ex:"Beyoncé · Pelé · Rihanna", a:"Mononym", o:["Pseudonym","Mononym","Hypocorism","Exonym"],
   why:"Mononym: someone known by one name.", id:"mononym"},
  {ex:"“Battle-sweat” for blood, in Old English poetry", a:"Kenning", o:["Euphemism","Calque","Kenning","Metaphor"],
   why:"Kenning: a poetic two-word name for something.", id:"kenning"},
  {ex:"Tutu", a:"Tautonym", o:["Tautonym","Palindrome","Semordnilap","Clipping"],
   why:"Tautonym: a word made of the same part said twice.", id:"tautonym"},
  {ex:"“Disgruntled”, but nobody is “gruntled”", a:"Unpaired word", o:["Antonym","Unpaired word","Litotes","Oxymoron"],
   why:"Unpaired word: its plain partner has fallen out of use.", id:"unpaired-word"},
  {ex:"“A damp squid” (for a damp squib)", a:"Eggcorn", o:["Spoonerism","Malapropism","Mondegreen","Eggcorn"],
   why:"Eggcorn: a misheard phrase that still sort of makes sense.", id:"eggcorn"},
  {ex:"“Stop being so pacific” (for specific)", a:"Malapropism", o:["Eggcorn","Malapropism","Spoonerism","Oronym"],
   why:"Malapropism: the wrong word, used because it sounds like the right one.", id:"malapropism"},
  {ex:"“You noble tons of soil” (for noble sons of toil)", a:"Spoonerism", o:["Spoonerism","Mondegreen","Oronym","Anagram"],
   why:"Spoonerism: swapping the first sounds of two words.", id:"spoonerism"},
  {ex:"Four candles · Fork handles", a:"Oronym", o:["Homophone","Spoonerism","Homonym","Oronym"],
   why:"Oronym: a phrase that sounds exactly like a different phrase.", id:"oronym"},
  {ex:"“Round John Virgin” (for “round yon virgin”, in Silent Night)", a:"Mondegreen", o:["Mondegreen","Eggcorn","Malapropism","Spoonerism"],
   why:"Mondegreen: a misheard line from a song, poem or hymn.", id:"mondegreen"},
  {ex:"“Fan-flipping-tastic”", a:"Tmesis", o:["Portmanteau","Tmesis","Spoonerism","Kenning"],
   why:"Tmesis: splitting a word by dropping another word into the middle.", id:"tmesis"},
  {ex:"“He took his hat and his leave”", a:"Zeugma", o:["Oxymoron","Litotes","Metonym","Zeugma"],
   why:"Zeugma: one word doing two jobs at once.", id:"zeugma"},
  {ex:"“Hear the mellow wedding bells” (Edgar Allan Poe)", a:"Assonance", o:["Alliteration","Assonance","Consonance","Onomatopoeia"],
   why:"Assonance: repeated vowel sounds.", id:"assonance"},
  {ex:"Lick · Back · Shook", a:"Consonance", o:["Consonance","Assonance","Alliteration","Homophone"],
   why:"Consonance: repeated consonant sounds, here the k at the end.", id:"consonance"},
];

// Easter eggs, in the order they unlock. One per perfect bonus round, at most one a day.
// The ids match glossary.html, which reads the same saved list.
const EGGS = [
  {id:"pun", name:"Pun", def:"A joke that plays on a word with two meanings, or two words that sound alike.", eg:"I used to be a banker, but I lost interest."},
  {id:"verbing", name:"Verbing", def:"Turning a noun into a verb.", eg:"To google something."},
  {id:"compound-word", name:"Compound word", def:"Two whole words joined to make a new one.", eg:"Sun + flower = sunflower."},
  {id:"reduplication", name:"Reduplication", def:"A word built from a sound repeated with a small change.", eg:"Zigzag, chit-chat, hanky-panky."},
  {id:"eye-rhyme", name:"Eye rhyme", def:"Words that look as if they rhyme, but don't when you say them.", eg:"Love and move."},
  {id:"rebus", name:"Rebus", def:"A puzzle where pictures or symbols stand in for words or sounds.", eg:"I ♥ NY."},
  {id:"back-formation", name:"Back-formation", def:"A new word made by trimming a bit off a longer one.", eg:"Edit, made from editor."},
  {id:"anacronym", name:"Anacronym", def:"An acronym so familiar that people forget it ever was one.", eg:"Laser."},
  {id:"false-friend", name:"False friend", def:"A word that looks the same in another language but means something different.", eg:"French sensible means sensitive."},
  {id:"chiasmus", name:"Chiasmus", def:"A phrase that repeats itself in reverse order.", eg:"Eat to live, not live to eat."},
  {id:"malaphor", name:"Malaphor", def:"Two sayings accidentally mashed into one.", eg:"We'll burn that bridge when we come to it."},
  {id:"pleonasm", name:"Pleonasm", def:"Using more words than you need.", eg:"A free gift."},
  {id:"synecdoche", name:"Synecdoche", def:"A part of something used to mean the whole thing.", eg:"All hands on deck."},
  {id:"dysphemism", name:"Dysphemism", def:"A deliberately harsh word for something. The opposite of a euphemism.", eg:"Rust bucket for an old car."},
  {id:"snowclone", name:"Snowclone", def:"A well-worn phrase template you can fill with new words.", eg:"Grey is the new black."},
  {id:"tom-swifty", name:"Tom Swifty", def:"A pun hidden in the word describing how something was said.", eg:"“I've lost my crayons,” said Tom colourlessly."},
  {id:"ambigram", name:"Ambigram", def:"A word that still reads correctly when you turn it upside down.", eg:"SWIMS, in capitals."},
  {id:"ghost-word", name:"Ghost word", def:"A word that only exists because of a mistake.", eg:"Dord, printed in a 1934 dictionary by error."},
  {id:"hapax-legomenon", name:"Hapax legomenon", def:"A word that appears only once in a whole body of writing.", eg:"Honorificabilitudinitatibus, used once in all of Shakespeare."},
];

// ---- Golden bonus ----
// Unlocks on every 7th day of a winning streak (day 7, 14, 21...). Same rules as the daily puzzle,
// but it doesn't touch your stats. Everyone eligible on a given date gets the same golden puzzle.
// Solving a golden puzzle whose type is also an Easter egg unlocks that egg too.
const GOLD_TYPES = {
  "contronym":     {name:"Contronym", ask:"One word, two opposite meanings", def:"One word with two opposite meanings.", eg:"dust: to sprinkle it on, or wipe it off"},
  "demonym":       {name:"Demonym", ask:"What do you call someone from", def:"The name for people from a place.", eg:"someone from Glasgow is a Glaswegian"},
  "toponym":       {name:"Toponym", ask:"Which word is named after the place", def:"A word that comes from a place name.", eg:"cheddar, from the village in Somerset"},
  "retronym":      {name:"Retronym", ask:"What's the new name for", def:"A new name for an old thing, needed because something newer came along.", eg:"acoustic guitar, once electric ones arrived"},
  "backronym":     {name:"Backronym", ask:"Which word was this phrase made up to fit?", def:"A phrase invented afterwards to fit a word that already existed.", eg:"“Golf: gentlemen only, ladies forbidden” (it isn't)"},
  "capitonym":     {name:"Capitonym", ask:"One spelling, and a capital letter changes it", def:"A word that changes meaning when it gets a capital letter.", eg:"march along, the month of March"},
  "eggcorn":       {name:"Eggcorn", ask:"Fix the misheard phrase", def:"A misheard word or phrase that still sort of makes sense.", eg:"“old-timers' disease” for Alzheimer's"},
  "endonym":       {name:"Endonym", ask:"What does it call itself?", def:"The name a place or people use for themselves.", eg:"Italia for Italy"},
  "euphemism":     {name:"Euphemism", ask:"Say it more gently", def:"A gentler way of saying something blunt or awkward.", eg:"let go, for sacked"},
  "heteronym":     {name:"Heteronym", ask:"Same spelling, different sound", def:"Spelt the same, but said differently and with a different meaning.", eg:"lead the way, a lead pipe"},
  "holonym":       {name:"Holonym", ask:"They're all part of one thing", def:"The whole thing that a part belongs to.", eg:"car is the holonym of wheel"},
  "homonym":       {name:"Homonym", ask:"One word covers both", def:"Spelt and said the same, but with a different meaning.", eg:"a bat that flies, a cricket bat"},
  "hypocorism":    {name:"Hypocorism", ask:"What's the friendly short form of", def:"A pet name or shortened, friendly form of a name.", eg:"Liz for Elizabeth"},
  "initialism":    {name:"Initialism", ask:"Which letters stand for", def:"Like an acronym, but you say each letter separately.", eg:"DIY"},
  "kenning":       {name:"Kenning", ask:"What does this kenning mean?", def:"A poetic two-word name for something, from Old English and Norse poetry.", eg:"bone-house for the body"},
  "litotes":       {name:"Litotes", ask:"What does it really mean?", def:"Saying something by denying its opposite. A very British habit.", eg:"not bad, meaning good"},
  "metonym":       {name:"Metonym", ask:"What does it stand for?", def:"Something closely linked to a thing, used to stand in for it.", eg:"Downing Street for the government"},
  "onomatopoeia":  {name:"Onomatopoeia", ask:"Which word sounds like", def:"A word that sounds like the noise it describes.", eg:"sizzle"},
  "oronym":        {name:"Oronym", ask:"It sounds like another phrase", def:"A phrase that sounds exactly like a different phrase.", eg:"four candles, fork handles"},
  "oxymoron":      {name:"Oxymoron", ask:"Finish the oxymoron", def:"Two words with opposite meanings used together.", eg:"bittersweet"},
  "spoonerism":    {name:"Spoonerism", ask:"Unswap the spoonerism", def:"Swapping the first sounds of two words, usually by accident.", eg:"“tease my ears” for “ease my tears”"},
  "tautonym":      {name:"Tautonym", ask:"Find the word made of two identical halves", def:"A word made of the same part said twice.", eg:"bonbon"},
  "anacronym":     {name:"Anacronym", ask:"Which everyday word started as", def:"An acronym so familiar that people forget it ever was one.", eg:"scuba"},
  "aptagram":      {name:"Aptagram", ask:"Finish the aptagram", def:"An anagram whose new words suit the original's meaning.", eg:"the eyes → they see"},
  "back-formation":{name:"Back-formation", ask:"Trim it back", def:"A new word made by trimming a bit off a longer one.", eg:"burgle, from burglar"},
  "compound-word": {name:"Compound word", ask:"Join two whole words", def:"Two whole words joined to make a new one.", eg:"sun + flower = sunflower"},
  "false-friend":  {name:"False friend", ask:"It looks English, but what does it mean?", def:"A word that looks the same in another language but means something different.", eg:"Spanish embarazada means pregnant, not embarrassed"},
  "idiom":         {name:"Idiom", ask:"Finish the idiom", def:"A phrase that means something different from its individual words.", eg:"under the weather, meaning ill"},
  "rebus":         {name:"Rebus", ask:"What does the symbol stand for?", def:"A puzzle where pictures or symbols stand in for words or sounds.", eg:"B4 for before"},
  "reduplication": {name:"Reduplication", ask:"Finish the reduplication", def:"A word built from a sound repeated with a small change.", eg:"chit-chat"},
  "simile":        {name:"Simile", ask:"Finish the simile", def:"Comparing two things using “like” or “as”.", eg:"as brave as a lion"},
};
const GOLD = [
  {type:"contronym", clue:"To fasten · To run away", sub:"One word means both.", answer:"bolt"},
  {type:"spoonerism", clue:"Fighting a liar", sub:"Swap the first sounds back: lighting a ____.", answer:"fire"},
  {type:"demonym", clue:"Manchester", sub:"Someone from there is a ____.", answer:"mancunian", free:true},
  {type:"simile", clue:"As cool as a ____", sub:"A salad vegetable.", answer:"cucumber"},
  {type:"retronym", clue:"A phone with a cord, fixed to the wall", sub:"The name it needed once mobiles came along.", answer:"landline"},
  {type:"capitonym", clue:"Shine your shoes · From Warsaw", sub:"One spelling: a capital letter changes it.", answer:"polish"},
  {type:"kenning", clue:"Whale-road", sub:"Old English poets' name for it.", answer:"sea", close:"ocean"},
  {type:"toponym", clue:"Nîmes, in the south of France", sub:"A tough cotton cloth named “de Nîmes”.", answer:"denim"},
  {type:"heteronym", clue:"Take a ____ · Tie a ____", sub:"Same spelling, different sound.", answer:"bow"},
  {type:"idiom", clue:"A piece of ____", sub:"It means something's easy.", answer:"cake"},
  {type:"onomatopoeia", clue:"The sound a bee makes", sub:"The word copies the noise.", answer:"buzz", close:"hum drone"},
  {type:"endonym", clue:"Wales", sub:"What the Welsh call it.", answer:"cymru", free:true},
  {type:"oxymoron", clue:"Deafening ____", sub:"The quiet half of the pair.", answer:"silence"},
  {type:"backronym", clue:"Save Our Souls", sub:"Made up to fit a distress signal.", answer:"sos", free:true},
  {type:"holonym", clue:"Petal · Stem · Leaf", sub:"They're all parts of one thing.", answer:"flower", close:"plant"},
  {type:"anacronym", clue:"Thomas A. Swift's Electric Rifle", sub:"A stun gun. Nobody remembers it's an acronym.", answer:"taser", free:true},
  {type:"euphemism", clue:"Died", sub:"A gentler way to say it: passed ____.", answer:"away", close:"on"},
  {type:"homonym", clue:"A riverside · A place for your money", sub:"Same spelling, same sound, two meanings.", answer:"bank"},
  {type:"reduplication", clue:"Zig-____", sub:"A sound repeated with a small change.", answer:"zag"},
  {type:"litotes", clue:"Not bad", sub:"What it really means.", answer:"good", close:"great fine decent"},
  {type:"hypocorism", clue:"Robert", sub:"A friendly short form. Rhymes with job.", answer:"bob", free:true, close:"rob bobby robbie"},
  {type:"aptagram", clue:"Dormitory → dirty ____", sub:"Rearrange it into words that describe it.", answer:"room"},
  {type:"eggcorn", clue:"For all intensive purposes", sub:"What should “intensive” be?", answer:"intents"},
  {type:"tautonym", clue:"A North African grain dish", sub:"Two identical halves.", answer:"couscous"},
  {type:"metonym", clue:"The Crown", sub:"What it stands for.", answer:"monarchy", close:"king queen royals monarch royalty"},
  {type:"back-formation", clue:"Editor", sub:"The verb that was trimmed from it.", answer:"edit"},
  {type:"oronym", clue:"I scream", sub:"Sounds just like a frozen treat: ice ____.", answer:"cream"},
  {type:"compound-word", clue:"Rain + ____", sub:"What you see after a sunny shower.", answer:"rainbow"},
  {type:"initialism", clue:"British Broadcasting Corporation", sub:"Say each letter.", answer:"bbc", free:true},
  {type:"false-friend", clue:"Sensible (in French)", sub:"What it really means in English.", answer:"sensitive"},
  {type:"rebus", clue:"I ♥ NY", sub:"What does the heart stand for?", answer:"love"},
];
